task:
  name: Test (macOS with Tart)
  alias: Tests
  persistent_worker:
    labels:
      name: scaleway-m1
  env:
    CIRRUS_INTERNAL_TART_VM: ghcr.io/cirruslabs/macos-ventura-base:latest
    CIRRUS_INTERNAL_TART_SSH_PASSWORD: admin
    CIRRUS_INTERNAL_TART_SSH_USER: admin
  test_script:
    - go test -v -run TestWorkerIsolationTart ./...
    - go test -v -run TestExecutorTart ./...
